# Generated by Django 5.2.8 on 2025-11-21 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_product_is_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "permissions": [("can_unpublish_product", "Can unpublish product")],
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
            },
        ),
    ]
